// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBiC1Kogett1JjJv7Np2-JzUv58M1euYuw',
    appId: '1:1072062903150:web:ec8519d00d18889eca077f',
    messagingSenderId: '1072062903150',
    projectId: 'apps4rent-28287',
    authDomain: 'apps4rent-28287.firebaseapp.com',
    storageBucket: 'apps4rent-28287.appspot.com',
    measurementId: 'G-1VX1VK1F3F',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAp7G6NrEm6JXTysfRUvgadaX3uZLrIEIY',
    appId: '1:1072062903150:android:5acf5e2766a2b26fca077f',
    messagingSenderId: '1072062903150',
    projectId: 'apps4rent-28287',
    storageBucket: 'apps4rent-28287.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA_D-3VGT0DJ-09trHsckPbbHNT_XNLsjM',
    appId: '1:1072062903150:ios:bfc3416fb0d72a59ca077f',
    messagingSenderId: '1072062903150',
    projectId: 'apps4rent-28287',
    storageBucket: 'apps4rent-28287.appspot.com',
    iosBundleId: 'com.example.apps4rent',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA_D-3VGT0DJ-09trHsckPbbHNT_XNLsjM',
    appId: '1:1072062903150:ios:79d425e7629a60afca077f',
    messagingSenderId: '1072062903150',
    projectId: 'apps4rent-28287',
    storageBucket: 'apps4rent-28287.appspot.com',
    iosBundleId: 'com.example.apps4rent.RunnerTests',
  );
}
